phpmd:
    class: piotrpasich\CodeQualityThreshold\Tool\Phpmd

phpcs:
    class: piotrpasich\CodeQualityThreshold\Tool\Phpcs

phpcpd:
    class: piotrpasich\CodeQualityThreshold\Tool\Phpcpd

Phpdcd:
    class: piotrpasich\CodeQualityThreshold\Tool\Phpdcd
