phpmd:
    class: piotrpasich\CodeQualityThreshold\Tool\Phpmd
    options:
        threshold: 42
        directory: app
        rules: cleancode,codesize,unusedcode
        command: vendor/phpmd/phpmd/src/bin/phpmd
